language: python
python:
  - "3.5.1"
  - "3.5"
  - "3.6"
#  - "nightly"
install:
    - "pip install -U -r requirements-test.txt"
script:
    PYTHONPATH=. pytest -vv --cov aiorun --cov-report term-missing tests/
after_success:
    coveralls
