language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
    - "pip install -r requirements-test.txt"
script:
    PYTHONPATH=. py.test -vv --cov aiorun --cov-report term-missing tests/
after_success:
    coveralls
